name: macod-p7zip-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: macos-Check
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: build 7za & check
      run: |
        mkdir macos-p7zip
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Alone
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
        git clone  https://github.com/jinfeihan57/p7zip_test_utils.git
        cd p7zip_test_utils/check
        bash check_7za.sh 7za
    - name: build 7zz & check
      run: |
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Alone2
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
        git clone  https://github.com/jinfeihan57/p7zip_test_utils.git
        cd p7zip_test_utils/check
        bash check.sh 7zz
    - name: build 7z.so
      run: |
        export PROJECT_ROOT=`pwd`
        cd CPP/7zip/Bundles/Format7zF
        make -f makefile.gcc
        INSTALL_PREFIX=$PROJECT_ROOT/macos-p7zip make -f makefile.gcc install
